In [102]:
import math
import numpy as np
np.random.seed(0)

In [103]:
# First I am going to define single head attention from scratch.

<h2><center>Single Head Self Attention<h2>

In [104]:
# HYPERPARAMETERS:
sequence_length = 4
embedding_dimension = 8
# I defined hyperparameters for the attention mechanism.
# I need sequence length, embedding dimension, head dimension.
# Each word should have many different concepts, so embedding dimension is 8.

In [105]:
# TOKEN EMBEDDINGS:
token_embeddings = np.random.randn(sequence_length, embedding_dimension)
print('token_embeddings:')
print(token_embeddings.shape)
print(token_embeddings)

token_embeddings:
(4, 8)
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
   0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351  0.76103773  0.12167502
   0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574 -2.55298982  0.6536186
   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877
   0.15494743  0.37816252]]


In [106]:
# CREATING 3 DiFFERENT PRESPECTIVES FOR EACH TOKEN
# Query, Key, Value:
# These are weight metrices, in my notebook, these are randomm. But in transformer model, learned during training.
# Query (Q): what I am  looking for.
# Key (K): What can I offer??
# Value (V): What is my actual content?

# Each word becomes question asker 
W_q = np.random.randn(embedding_dimension,embedding_dimension)
# Each word becomes answer giver
W_k = np.random.randn(embedding_dimension, embedding_dimension)
# Each word becomes actual content
W_v =np.random.randn(embedding_dimension, embedding_dimension)
print('\nWeight matrices shapes:')
print("W_q shape:",W_q.shape)
print(W_q)
print("\nW_k shape:",W_k.shape)
print(W_k)
print("\nW_v shape:",W_v.shape)
print(W_v)


Weight matrices shapes:
W_q shape: (8, 8)
[[-0.88778575 -1.98079647 -0.34791215  0.15634897  1.23029068  1.20237985
  -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218 -0.4380743
  -1.25279536  0.77749036]
 [-1.61389785 -0.21274028 -0.89546656  0.3869025  -0.51080514 -1.18063218
  -0.02818223  0.42833187]
 [ 0.06651722  0.3024719  -0.63432209 -0.36274117 -0.67246045 -0.35955316
  -0.81314628 -1.7262826 ]
 [ 0.17742614 -0.40178094 -1.63019835  0.46278226 -0.90729836  0.0519454
   0.72909056  0.12898291]
 [ 1.13940068 -1.23482582  0.40234164 -0.68481009 -0.87079715 -0.57884966
  -0.31155253  0.05616534]
 [-1.16514984  0.90082649  0.46566244 -1.53624369  1.48825219  1.89588918
   1.17877957 -0.17992484]
 [-1.07075262  1.05445173 -0.40317695  1.22244507  0.20827498  0.97663904
   0.3563664   0.70657317]]

W_k shape: (8, 8)
[[ 0.01050002  1.78587049  0.12691209  0.40198936  1.8831507  -1.34775906
  -1.270485    0.96939671]
 [-1.17312341  1.94362119 -0.4

In [107]:
# In mumpy @ is matrix multiplication.
# Spurce: https://numpy.org/doc/2.1/reference/generated/numpy.matmul.html?

In [108]:
# This is like asking: For each word, what is its query vector, what it wants from others?
Q =token_embeddings @ W_q  
K= token_embeddings @ W_k 
V = token_embeddings @ W_v 
print("\nQury shape:shape:",Q.shape)
print(Q)
print('\nKey shape:',K.shape)
print(K)
print("\nValue shape:",V.shape)
print(V)


Qury shape:shape: (4, 8)
[[-5.14329841 -2.44018414 -6.52863207  0.51116581  0.49852547  2.30066161
  -0.30223837 -3.7632453 ]
 [-1.07542068  0.32630062 -2.83567179  0.30794017 -1.45413732  0.1395637
  -0.50192854 -1.8374508 ]
 [-1.59413038 -2.77831285  5.21829436 -3.60000123  5.23621887  2.22688508
  -0.94649399  0.02482593]
 [ 0.78431113 -4.38895788 -0.21823792 -2.46930639  1.27533979  3.27168043
   2.0709697  -0.95462633]]

Key shape: (4, 8)
[[ 2.61868617  5.32088725 -2.21285007  7.40470497  2.23937946 -2.9171613
  -3.10951834  9.45599857]
 [ 1.33168829 -0.28177695 -0.7635857   2.24792734 -1.18126044  0.01953494
  -0.52321681  4.300593  ]
 [ 0.93855483  4.05985713  1.44426359 -0.76083027  2.082033   -1.62971644
   0.80743105  0.46588887]
 [ 3.58543568  1.6722437   0.04461782  0.93055765 -1.35165464 -4.97687382
  -6.66446176  2.64844173]]

Value shape: (4, 8)
[[ 0.76755231 -2.83248751 -0.45197153 -0.23697617 -2.11506695  6.06838635
  -2.46877688 -1.27516318]
 [ 1.37649418 -3.33332497

In [109]:
# T stands for transpose to swap rows and columns in matrix for computing dot product.
#source:https://jtlicardo.com/blog/self-attention-mechanism

In [110]:
# Without scaling:
attention_scores = (Q @ K.T)
attention_scores

array([[-48.46115302, -16.59744429, -29.26081294, -42.41358894],
       [-12.00252904,  -4.5856329 ,  -8.5306868 ,  -3.40056023],
       [-48.75427426, -18.95702473,   4.01997717, -25.26571042],
       [-61.25555622,  -9.73463472, -16.96808943, -41.17160952]])

In [111]:
# Here I can see that the attention scores  are too big
# I am going to use softmax to convert them to probabilities.
# But with this big values, softmax will focus on large values.
# I need to scale them.
# Source: https://www.youtube.com/watch?v=0PjHri8tc1c

In [112]:
# ATTENSION SCORE: 
# Now I am going to calculate attention scores that I can see how each word attends to other words.
scale= np.sqrt(embedding_dimension)
attention_scores = (Q @ K.T)/ scale
# If I can explain clearly: 
# Word1 asks Q1, Word2 answers with K2 calculate match score
# Higher score = We understand each other well
# For example, scores: Word1 with Word2 = 0.9 which is high, Word1 with Word3 = 0.5, Word1 with Word4 = 0.1
print("\nAttention scores shape:",attention_scores.shape)
print(attention_scores)
# Now it looks better.
# 48/2.8 = 17.13


Attention scores shape: (4, 4)
[[-17.13360496  -5.8680827  -10.34525963 -14.99546818]
 [ -4.24353484  -1.62126606  -3.01605324  -1.2022796 ]
 [-17.23723897  -6.70232037   1.42127656  -8.93277758]
 [-21.6571096   -3.44171311  -5.99912555 -14.55636214]]


In [113]:
# ATTENTION WEIGHT:

# Here, raw score is turned into probabilities like saying pay X%  attention here
def softmax(x, axis=-1):
    x_shifted= x - np.max(x, axis=axis,keepdims=True)
    exp_x= np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=axis,keepdims=True)
attention_weights= softmax(attention_scores)

# Softmax makes things differentiable and focuses on high scores while ignoring lows.
print("\nAttention weights shape:",attention_weights.shape)
print(attention_weights)
# here, the softmax made values in probability form.
# Source: https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python


Attention weights shape: (4, 4)
[[1.26615123e-05 9.88643541e-01 1.12363822e-02 1.07415409e-04]
 [2.55682235e-02 3.51995745e-01 8.72547416e-02 5.35181290e-01]
 [7.88074176e-09 2.96363089e-04 9.99671776e-01 3.18528907e-05]
 [1.13953720e-08 9.28057076e-01 7.19290918e-02 1.38211425e-05]]


In [114]:
# CREATING NEW UNDERSTANDING:
# Here, each word creates a new version of itself by mixing other words information.
# The model learns contextual meaning
# Each word becomes smarter by considering its neighbors 
# For example: word bank can learn from account,bank account.
Attention_output= attention_weights @V
print("\nAttention output shape:",Attention_output.shape)
print(Attention_output)


Attention output shape: (4, 8)
[[ 1.34183768 -3.22302592  0.30127404  0.28646352  0.02777836  1.73761364
  -1.28251356  1.30731129]
 [-1.5554347   0.47820738  2.50183185  0.44145363 -1.2631944   1.10857787
   0.23516515 -2.13999061]
 [-1.65893093  6.42668607  0.5231314   1.19786552 -1.64813149 -3.65713874
  -6.388647   -7.97541717]
 [ 1.15802999 -2.63100225  0.31453943  0.34241596 -0.07491754  1.40636373
  -1.5963526   0.7378006 ]]


<h2><center>Multi Head Self attention and masking from scratch<h2>

In [115]:
# In here  I am going to create multi head attention from scratch,  multiple heads self attention mechanism is like having many brains.
# from what I understand, it helps the model focus on different parts of the input parallelly.
# In single head attention, I have one set of Q, K, V  per token. but here, I will have multiple sets of Q, K, V per token.

In [116]:
# For multi head attention, I am going to define some hyperparameters
# The frist one is going to be:
# Number of head attention, what I understand, it is like number of specialists for monitoring attention pattern
# While I was reading some articles, some LLMs use 128 heads.
# Second one is going to be: 
# I have to give equal capacity to each head to learn the patterns, So I divide the embedding dimension by number of heads.
num_heads = 2
# I have already  embedding_dimension which is 8, so each head can get 4 dimension to learn patterns.
head_dimension = embedding_dimension // num_heads 
head_dimension

4

In [117]:
# INPUT EMBEDDINGS:
# I need reproducible numbers
# transformer models use pretrained embeddings like word2vec, GloVe, FastText,BERT.
# real models get semantic meaning, similar words have similar vectors.
# In here, each word  has 8 traits.
token_embeddings_multi_heads = np.random.randn(sequence_length, embedding_dimension)
print("token_embeddings:", token_embeddings_multi_heads.shape)
print(token_embeddings_multi_heads)
# In output, I can see that 4 tokens, each has 8 demensions you know that is like 8 personality 
# What I learned, token embeddings give passport to each word in the sentence.

token_embeddings: (4, 8)
[[-1.54079701  0.06326199  0.15650654  0.23218104 -0.59731607 -0.23792173
  -1.42406091 -0.49331988]
 [-0.54286148  0.41605005 -1.15618243  0.7811981   1.49448454 -2.06998503
   0.42625873  0.67690804]
 [-0.63743703 -0.39727181 -0.13288058 -0.29779088 -0.30901297 -1.67600381
   1.15233156  1.07961859]
 [-0.81336426 -1.46642433  0.52106488 -0.57578797  0.14195316 -0.31932842
   0.69153875  0.69474914]]


In [118]:
# PROJECTION MATRICES:
# My raw word embeddings are not ready for attention, the next step is to transform  them into Query projections, Key projections, Value projections.
# Search query, from what I understand, this creates search query from learning and extracting of word that are relavant to ask questions.
# Key projection matrix learns to extract  that aspect of the word embeddings that  make useful 
# Value projection matrix makes the actual content 
# Output projection matrix,   
# Overall, I can say that projection matrices helps the model to learn different  roles for the same word.

W_Q = np.random.randn(embedding_dimension, embedding_dimension)
W_K =np.random.randn(embedding_dimension, embedding_dimension)
W_V= np.random.randn(embedding_dimension, embedding_dimension)
W_OutPut =np.random.randn(embedding_dimension, embedding_dimension)
# PROJECTING QUERY, KEY, VALUE:
# Now, I can create 3 different roles, Google News dataset model has 300 dimension vectors.
Q_Multi_Head = token_embeddings_multi_heads @ W_Q
K_Multi_Head = token_embeddings_multi_heads @ W_K
V_Multi_Head = token_embeddings_multi_heads @ W_V

print("Query Projection Matrix")
print(W_Q.shape)
print(W_Q)
print("\nKey Projection Matrix")
print(W_K.shape)
print(W_K)
print('\nValue Projection Matrix')
print(W_V.shape)
print(W_V)
print('\nOutput Projection Matrix')
print(W_OutPut.shape)
print(W_OutPut)

# What I can see here, from 8 demensions of each word, Query, Key, Value projections are created.

Query Projection Matrix
(8, 8)
[[-0.72559738 -1.38336396 -1.5829384   0.61037938 -1.18885926 -0.50681635
  -0.59631404 -0.0525673 ]
 [-1.93627981  0.1887786   0.52389102  0.08842209 -0.31088617  0.09740017
   0.39904635 -2.77259276]
 [ 1.95591231  0.39009332 -0.65240858 -0.39095338  0.49374178 -0.11610394
  -2.03068447  2.06449286]
 [-0.11054066  1.02017271 -0.69204985  1.53637705  0.28634369  0.60884383
  -1.04525337  1.21114529]
 [ 0.68981816  1.30184623 -0.62808756 -0.48102712  2.3039167  -1.06001582
  -0.1359497   1.13689136]
 [ 0.09772497  0.58295368 -0.39944903  0.37005589 -1.30652685  1.65813068
  -0.11816405 -0.6801782 ]
 [ 0.66638308 -0.46071979 -1.33425847 -1.34671751  0.69377315 -0.15957344
  -0.13370156  1.07774381]
 [-1.12682581 -0.73067775 -0.38487981  0.09435159 -0.04217145 -0.28688719
  -0.0616264  -0.10730528]]

Key Projection Matrix
(8, 8)
[[-0.71960439 -0.81299299  0.27451636 -0.89091508 -1.15735526 -0.31229225
  -0.15766702  2.2567235 ]
 [-0.70470028  0.94326072  0.

In [119]:
print("\nQ Multi Head shape:",Q_Multi_Head.shape)
print(Q_Multi_Head)
print('\nK Multi Head shape:',K_Multi_Head.shape)
print(K_Multi_Head)
print("\nV Multi Head shape:",V_Multi_Head.shape)
print(V_Multi_Head)


Q Multi Head shape: (4, 8)
[[ 4.47578083e-01  2.54158236e+00  4.76948068e+00  1.43119702e+00
  -7.66056412e-02  1.51768244e+00  7.13659381e-01 -1.48918392e+00]
 [-2.40950851e+00  1.22335049e+00  3.49875274e-01 -6.37415661e-01
   6.58371685e+00 -4.35317936e+00  1.96374714e+00  9.28000610e-01]
 [ 1.79169258e-01 -2.24789816e+00  4.20871333e-03 -2.75134780e+00
   2.96218145e+00 -2.82659596e+00  8.22140298e-01  2.41471879e+00]
 [ 4.25707194e+00 -3.63385788e-01 -5.73904191e-01 -2.76667391e+00
   2.70999678e+00 -1.13129300e+00 -6.73264833e-01  5.53626257e+00]]

K Multi Head shape: (4, 8)
[[-0.23032457  4.10990919 -0.69681036  2.80410693  2.87751884  0.82791391
   1.16373507 -4.4380722 ]
 [ 2.69795373 -2.48875856 -2.25648205 -3.11750308 -3.3461424  -0.41730036
  -2.65033961  0.57047362]
 [-0.1029719  -2.62172077 -1.53275905  0.17017102 -0.15136576  0.63415146
  -0.43448628 -1.15468744]
 [ 1.19009161 -2.29589606 -1.80537549  2.98481686 -0.82326731  1.52982212
   2.56926124 -2.68413999]]

V Mul

In [120]:
# MULTI HEAD SPLITTING:
# iam going to create a function to split 8 dimension into 2 heads.
def split_heads(Input, num_heads):
    return Input.reshape(sequence_length, num_heads, head_dimension).transpose(1, 0, 2)

# COMBINING HEADS BACK:
def mergee_heads(heads):
    return heads.transpose(1, 0, 2).reshape(sequence_length, embedding_dimension)

# I defined the softmax function already above, when I printed projections, all 8 demensions are printed together or worked together.
# here each head  have half of that. 

In [121]:
# Now I can split the projections into two heads.
Q_heads = split_heads(Q_Multi_Head, num_heads)
K_heads= split_heads(K_Multi_Head, num_heads)
V_heads =split_heads(V_Multi_Head,num_heads)

print('Q heads shape:',Q_heads.shape)
print(Q_heads)
print("K heads shape:",K_heads.shape)
print(K_heads)
print("V heads shape:",V_heads.shape)
print(V_heads)

Q heads shape: (2, 4, 4)
[[[ 4.47578083e-01  2.54158236e+00  4.76948068e+00  1.43119702e+00]
  [-2.40950851e+00  1.22335049e+00  3.49875274e-01 -6.37415661e-01]
  [ 1.79169258e-01 -2.24789816e+00  4.20871333e-03 -2.75134780e+00]
  [ 4.25707194e+00 -3.63385788e-01 -5.73904191e-01 -2.76667391e+00]]

 [[-7.66056412e-02  1.51768244e+00  7.13659381e-01 -1.48918392e+00]
  [ 6.58371685e+00 -4.35317936e+00  1.96374714e+00  9.28000610e-01]
  [ 2.96218145e+00 -2.82659596e+00  8.22140298e-01  2.41471879e+00]
  [ 2.70999678e+00 -1.13129300e+00 -6.73264833e-01  5.53626257e+00]]]
K heads shape: (2, 4, 4)
[[[-0.23032457  4.10990919 -0.69681036  2.80410693]
  [ 2.69795373 -2.48875856 -2.25648205 -3.11750308]
  [-0.1029719  -2.62172077 -1.53275905  0.17017102]
  [ 1.19009161 -2.29589606 -1.80537549  2.98481686]]

 [[ 2.87751884  0.82791391  1.16373507 -4.4380722 ]
  [-3.3461424  -0.41730036 -2.65033961  0.57047362]
  [-0.15136576  0.63415146 -0.43448628 -1.15468744]
  [-0.82326731  1.52982212  2.569261

In [122]:
multi_head_scale = np.sqrt(head_dimension)

attention_weight_multi_head= np.zeros((num_heads, sequence_length, sequence_length))
head_outputs= np.zeros((num_heads,sequence_length,head_dimension))

# To process each head separately, I am going to use for loop.
for head in range(num_heads):
    scores_multi_head = (Q_heads[head] @K_heads[head].T) /multi_head_scale             
    weights= softmax(scores_multi_head)        
    out= weights @V_heads[head]                              

    attention_weight_multi_head[head] = weights
    head_outputs[head]= out

Combined_output= mergee_heads(head_outputs)
# What i noticed here form reeading 
# To mix information across both heads, I am going to use output projection matrix.
# Because in real models,  heads can collaborate. not stay isolated
Output_projection = Combined_output @ W_OutPut
print("attention_probability:", attention_weight_multi_head.shape)
print(attention_weight_multi_head)

print("\nOutput", head_outputs.shape)
print(head_outputs)
print("\nCombined output shape:",Combined_output.shape)
print(Combined_output)
print("\nFinal output shape:",Output_projection.shape)
print(Output_projection)
print("\nRow sums per head:\n", np.round(attention_weight_multi_head.sum(axis=-1), 4))

attention_probability: (2, 4, 4)
[[[9.99963332e-01 1.53870247e-07 4.10053267e-06 3.24137406e-05]
  [9.67739343e-01 2.52258338e-03 2.70362840e-02 2.70178972e-03]
  [1.33154827e-07 9.90113425e-01 9.72887147e-03 1.57570489e-04]
  [1.04818042e-07 9.99969812e-01 2.26947317e-05 7.38823758e-06]]

 [[5.18500317e-01 1.57476567e-03 2.46516988e-02 4.55273218e-01]
  [9.99921946e-01 4.59571476e-09 6.80848552e-05 9.96497395e-06]
  [6.76457873e-01 3.44044068e-02 2.73665270e-01 1.54724505e-02]
  [5.13095363e-04 8.55991247e-01 1.43312410e-01 1.83247828e-04]]]

Output (2, 4, 4)
[[[-1.45148693  2.15872919  1.57714082  1.54180617]
  [-1.3744429   2.12347454  1.4671084   1.67576157]
  [ 1.30218726  0.24450175 -1.75912919  9.16607769]
  [ 1.30594122  0.23714176 -1.75543164  9.2020129 ]]

 [[-3.31628422 -1.02623844 -1.22293786 -0.07069307]
  [-4.85507384 -0.54222589 -0.25492793  1.19276607]
  [-2.73979657 -0.74201718  0.11153973  1.16815948]
  [ 4.29976396 -0.16093631 -0.50145802  3.08532927]]]

Combined out

In [123]:
# Sources:
# https://www.geeksforgeeks.org/nlp/multi-head-attention-mechanism
# https://www.datacamp.com/de/tutorial/multi-head-attention-transformers
# https://magazine.sebastianraschka.com/p/understanding-and-coding-self-attention
# https://www.kaggle.com/discussions/general/506393
# https://datajourney24.substack.com/p/inside-the-transformer-attention
# https://sungwookyoo.github.io/tips/study/Multihead_Attention
# https://blog.dailydoseofds.com/p/implement-attention-is-all-you-need
# https://agrimpaneru.com.np/blog/multi-head-attention-pytorch/
# https://medium.com/%40wangdk93/multihead-attention-from-scratch-6fd6f99b9651
# https://www.digitalocean.com/community/tutorials/multi-head-attention-simple-explained?
# For debugging, I used QWEN3 MAX model 

<h2><center>Masked Multi Head Attention<h2>

In [124]:
# what I learned:
# in causal masking, each head STILL must compute its own scores from its own Q and K.
# The mask shape is the same for all heads, but the scores must be fresh per head.


# To force the model to predict next word.
def causal_mask(sequence_length):
    return np.triu(np.ones((sequence_length, sequence_length), dtype=bool), k=1)

mask = causal_mask(sequence_length)

masked_attention_weights = np.zeros((num_heads, sequence_length, sequence_length))
masked_head_outputs = np.zeros((num_heads, sequence_length, head_dimension))


for head in range(num_heads):
    scores =(Q_heads[head] @ K_heads[head].T) /multi_head_scale
    scores[mask] =-np.inf 
    weights =softmax(scores)
    out = weights @ V_heads[head]

    masked_attention_weights[head] = weights
    masked_head_outputs[head] = out
masked_combined = mergee_heads(masked_head_outputs)
masked_output_projection = masked_combined @ W_OutPut

print("Causal mask:")
print(mask.astype(int))
print('\nMasked attention weights shape:', masked_attention_weights.shape)
print(masked_attention_weights)
print('\nRow sums per head, should all be 1:')
print(np.round(masked_attention_weights.sum(axis=-1), 4))
print("\nMasked output shape:", masked_output_projection.shape)
print(masked_output_projection)
# row sums are 1 and lower triangle shows each token only attends to itself and past tokens.
# position  0 can only see itself, position 1 sees 0 and 1
# https://www.mindspore.cn/docs/api/en/r1.6/api_python/nn/mindspore.nn.Triu.html?
# I used QWEN for debugging. 

Causal mask:
[[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]

Masked attention weights shape: (2, 4, 4)
[[[1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [9.97400101e-01 2.59989938e-03 0.00000000e+00 0.00000000e+00]
  [1.33175811e-07 9.90269462e-01 9.73040470e-03 0.00000000e+00]
  [1.04818042e-07 9.99969812e-01 2.26947317e-05 7.38823758e-06]]

 [[1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [9.99999995e-01 4.59607348e-09 0.00000000e+00 0.00000000e+00]
  [6.87088820e-01 3.49450930e-02 2.77966087e-01 0.00000000e+00]
  [5.13095363e-04 8.55991247e-01 1.43312410e-01 1.83247828e-04]]]

Row sums per head, should all be 1:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Masked output shape: (4, 8)
[[ -5.06144461  -7.56165993   6.41021232  -0.61784537  -9.65421088
   10.26984802 -10.90175101  -3.57420706]
 [ -5.06584675  -7.58649065   6.44460978  -0.58503544  -9.60220312
   10.25698555 -10.85717862  -3.54607099]
 [ -5.3878216  -15.21007528  17.42658152  11.07972925  12.04879564
 

<h2><center>Positional Encoding<h2>

In [125]:
# POSITIONAL ENCODING:
# What I learnned: transformers have no idea about word order.
# RNN that process words one by one, attention treats all positions equally.

# so I need to inject position information into the embeddings.


def positional_encoding(sequence_len, d_model):
    position = np.arange(sequence_len)[:, np.newaxis]

    scaling_value = 10000**(np.arange(0, d_model, 2)/d_model)
    output_matrix = np.zeros((sequence_len, d_model))

    output_matrix[:, 0::2] = np.sin(position / scaling_value)
    output_matrix[:, 1::2] = np.cos(position / scaling_value)
    return output_matrix
                 
output_matrix = positional_encoding(sequence_length, embedding_dimension)
print("Positional encoding shape:", output_matrix.shape)
print(np.round(output_matrix, 4))
# each row is unique 
# Source: https://nlp.seas.harvard.edu/annotated-transformer/#positional-encoding               

Positional encoding shape: (4, 8)
[[ 0.      1.      0.      1.      0.      1.      0.      1.    ]
 [ 0.8415  0.5403  0.0998  0.995   0.01    1.      0.001   1.    ]
 [ 0.9093 -0.4161  0.1987  0.9801  0.02    0.9998  0.002   1.    ]
 [ 0.1411 -0.99    0.2955  0.9553  0.03    0.9996  0.003   1.    ]]


In [126]:
# Now I am gonna add positional encoding to the token embeddings.
# The model gets both meaning from embeddings and position from output matrix.
positioned_embeddings = token_embeddings_multi_heads + output_matrix
print('Positioned embeddings shape:', positioned_embeddings.shape)
print(positioned_embeddings)
# Now each  token knows where it is in the sentence and what it means.

Positioned embeddings shape: (4, 8)
[[-1.54079701  1.06326199  0.15650654  1.23218104 -0.59731607  0.76207827
  -1.42406091  0.50668012]
 [ 0.29860951  0.95635235 -1.05634902  1.77620227  1.50448438 -1.07003502
   0.42725873  1.67690754]
 [ 0.2718604  -0.81341865  0.06578875  0.6822757  -0.2890143  -0.6762038
   1.15433156  2.07961659]
 [-0.67224425 -2.45641682  0.81658508  0.37954852  0.17194866  0.68022162
   0.69453875  1.69474464]]


<h2><center>Encoder block<h2>

In [127]:
# Encoder block has this extracture : 
# Imput, multi head attention, add +  layer normalization and then output
# Now I am gonna  to build the encoder block

In [128]:
# LAYER NORMALIZATION:
# To normalize each token separately, before processing, I can use layer normalization.  
# calcaulating  average of all 8 demensions for token. 

def layer_normalization(x,epsilon = 0.00001):
    mean = x.mean(axis=-1, keepdims=True)
    variance= x.var(axis=-1,keepdims=True)
    normalized_x = (x -mean)/ np.sqrt(variance+ epsilon)
    return normalized_x
# In real models, layer normalization has learnable gamma and beta parameters.
# gamma scales the output, beta shifts it. here I skip them for simplicity.

# Source:  https://nlp.seas.harvard.edu/annotated-transformer/#encoder-and-decoder-stacks

In [129]:
# Using positioned embeddings as 
# I reuse the projection matrices

Q_enc = positioned_embeddings @ W_Q
K_enc = positioned_embeddings @ W_K
V_enc = positioned_embeddings @ W_V

Q_enc_heads = split_heads(Q_enc, num_heads)
K_enc_heads = split_heads(K_enc, num_heads)
V_enc_heads = split_heads(V_enc, num_heads)


encoding_head_outputs = np.zeros((num_heads, sequence_length, head_dimension))
for head in range(num_heads):
    scores = (Q_enc_heads[head] @ K_enc_heads[head].T) /multi_head_scale
    weights= softmax(scores)

    encoding_head_outputs[head] = weights @ V_enc_heads[head]
encoding_attention_out =mergee_heads(encoding_head_outputs) @ W_OutPut


# add input back to attention output, then normalize
encoder_x1 = layer_normalization(positioned_embeddings + encoding_attention_out)
print('After attention + first residual + normmalization shape:', encoder_x1.shape)
print('Mean per token:', np.round(encoder_x1.mean(axis=-1), 4))
print('Std per token:',np.round(encoder_x1.std(axis=-1), 4))

# 4 tokens and each token has 8 features.
# Mean near  0 and std near 1 again

After attention + first residual + normmalization shape: (4, 8)
Mean per token: [-0.  0.  0. -0.]
Std per token: [1. 1. 1. 1.]


In [130]:
# FEED FORWARD NETWORK: 
# The transformer model should learn nonlinear patterns.
# Here I have two linear layers with one relu activation in the middle.
latent_dimension= 16 
W_ff1 = np.random.randn(embedding_dimension, latent_dimension)
b_ff1 = np.zeros((latent_dimension))
W_ff2 = np.random.randn(latent_dimension,embedding_dimension)
b_ff2 = np.zeros((embedding_dimension))

def relu(x):
    return np.maximum(0, x)

ffn_hidden = relu(encoder_x1 @ W_ff1 + b_ff1)
ffn_output = ffn_hidden @ W_ff2 + b_ff2

encoder_x2 = layer_normalization(encoder_x1 + ffn_output)
print("After FFN + second residual + normalization shape:", encoder_x2.shape)
print("Mean per token:", np.round(encoder_x2.mean(axis=-1), 4))
print('Std per token:', np.round(encoder_x2.std(axis=-1), 4))
# I used QWEN3 for debugging.

After FFN + second residual + normalization shape: (4, 8)
Mean per token: [ 0. -0. -0.  0.]
Std per token: [1. 1. 1. 1.]


<h2><center>Decoder Block with Cross-Attention<h2>

In [131]:
# In simple way I can say cross attention is like bridge between encoder and decoder.
# Here I am gonna prepare the decoder input and decoder attention weights.

# Real models use target tokens shifted right.
# here I use random embeddings only to test

decoder_embeddings = np.random.randn(sequence_length,embedding_dimension)
decoder_positioned = decoder_embeddings +output_matrix

W_Q_decoder = np.random.randn(embedding_dimension, embedding_dimension)
W_K_decoder = np.random.randn(embedding_dimension, embedding_dimension)
W_V_decoder= np.random.randn(embedding_dimension, embedding_dimension)
W_Out_decoder = np.random.randn(embedding_dimension, embedding_dimension)

print("Decoder positioned embeddings shape:",decoder_positioned.shape)
print(decoder_positioned)

Decoder positioned embeddings shape: (4, 8)
[[ 1.84959125  0.78583334 -0.49901664  1.02135122 -0.91911344  1.19275385
  -0.36505522 -0.79132755]
 [ 0.78288443  0.22275921 -1.53258989  0.92787001  1.4993558   1.52125375
   0.61292719 -0.34149723]
 [ 1.3861958  -0.26769726  0.72771457  1.4026952  -1.33978206  0.9583992
  -0.75587086  0.94991391]
 [-0.75628092  0.32247787 -0.56345218  0.05639433  0.10458191 -0.07754904
  -0.42166331  0.1700309 ]]


In [132]:
# Cross attention + residual + normalization:


# The decoder can only see past tokens, not future ones.
# This prevents cheating during training.

Q_decoder = decoder_positioned @ W_Q_decoder
K_decoder = decoder_positioned @ W_K_decoder
V_decoder=decoder_positioned @ W_V_decoder

Q_dec_heads = split_heads(Q_decoder,num_heads)
K_dec_heads= split_heads(K_decoder,num_heads)
V_dec_heads =split_heads(V_decoder, num_heads)

dec_self_outputs = np.zeros((num_heads, sequence_length, head_dimension))

for head in range(num_heads):
    head_scores = (Q_dec_heads[head] @ K_dec_heads[head].T) / multi_head_scale
    head_scores[mask] = -np.inf
    head_weights = softmax(head_scores)
    dec_self_outputs[head] = head_weights @ V_dec_heads[head]

decoder_self_out = mergee_heads(dec_self_outputs) @ W_Out_decoder
decoder_x1 = layer_normalization(decoder_positioned + decoder_self_out)

print('Decoder after masked self attention + residual + normalization:')
print('Shape:', decoder_x1.shape)
print("Mean per token:", np.round(decoder_x1.mean(axis=-1), 4))
print("Std per token:", np.round(decoder_x1.std(axis=-1), 4))

Decoder after masked self attention + residual + normalization:
Shape: (4, 8)
Mean per token: [-0.  0. -0. -0.]
Std per token: [1. 1. 1. 1.]


In [133]:
# Cross attention + residual + normalization:

# first decoder attention let the decoder look at its own past
# this cell lets the decoder look at the encoder result
# so now the decoder is not only using its own history, it is also reading the encoded input
# that is why this part matters so much in translation and sequence to sequence models

# Creating the projection matrices for cross attention. 
W_Q_cross_attention = np.random.randn(embedding_dimension, embedding_dimension)
W_K_cross_attention = np.random.randn(embedding_dimension, embedding_dimension)
W_V_cross_attention = np.random.randn(embedding_dimension, embedding_dimension)
W_Out_cross_attention = np.random.randn(embedding_dimension, embedding_dimension)


Q_cross = decoder_x1 @ W_Q_cross_attention
K_cross = encoder_x2 @ W_K_cross_attention
V_cross = encoder_x2 @ W_V_cross_attention

Q_cross_heads = split_heads(Q_cross, num_heads)
K_cross_heads =split_heads(K_cross, num_heads)
V_cross_heads = split_heads(V_cross, num_heads)

cross_outputs = np.zeros((num_heads, sequence_length, head_dimension))

for head in range(num_heads):
    cross_scores = (Q_cross_heads[head] @ K_cross_heads[head].T)/multi_head_scale
    cross_weights= softmax(cross_scores)
    cross_outputs[head] =cross_weights @ V_cross_heads[head]

cross_out = mergee_heads(cross_outputs) @ W_Out_cross_attention
decoder_x2 = layer_normalization(decoder_x1+cross_out)

print('Decoder after cross attention + residual + normlization:')
print("Shape:", decoder_x2.shape)
print("Mean per token:", np.round(decoder_x2.mean(axis=-1), 4))
print("Std per token:", np.round(decoder_x2.std(axis=-1), 4))


Decoder after cross attention + residual + normlization:
Shape: (4, 8)
Mean per token: [-0. -0. -0.  0.]
Std per token: [1. 1. 1. 1.]


In [134]:
# Cross attention + residual + normalization:
# This is last part of the decoder block.

# Attention mixed information
# In this cell,  now FFN gives each token its own small neural network step
# then residual keeps the old path and layer norm keeps the values stable.

W_ff1_decoder = np.random.randn(embedding_dimension, latent_dimension)
b_ff1_decoder= np.zeros((latent_dimension,))
W_ff2_decoder = np.random.randn(latent_dimension,embedding_dimension)
b_ff2_decoder =np.zeros((embedding_dimension,))

hidden_decoder = relu(decoder_x2 @ W_ff1_decoder +b_ff1_decoder)
ffn_decoder_output = hidden_decoder @ W_ff2_decoder + b_ff2_decoder

decoder_x3 = layer_normalization(decoder_x2+ffn_decoder_output)

print('Decoder after fnn + residual + normalization:')
print('Shape:', decoder_x3.shape)
print("Mean per token:", np.round(decoder_x3.mean(axis=-1), 4))
print("Std per token:", np.round(decoder_x3.std(axis=-1), 4))
# decoder block still keeps the same size

Decoder after fnn + residual + normalization:
Shape: (4, 8)
Mean per token: [ 0. -0.  0.  0.]
Std per token: [1. 1. 1. 1.]


<h2><center>Output Layer<h2>

In [136]:
# OUTPUT LAYER: 

# In this cell, I am going to take the final decoder output decoder x3
# map it from model size to vocabulary size and turn those scores into probabilities
# Finally, I  pick the biggest probability at each position as the predicted token id

vocabulary_size = 20 
W_vocab = np.random.randn(embedding_dimension, vocabulary_size)
b_vocab = np.zeros((vocabulary_size,))
logits = decoder_x3 @ W_vocab +b_vocab

# applying softmax to get probability        
probabilities = softmax(logits, axis=-1)
predicted_token_ids = np.argmax(probabilities, axis=-1)

Predicted_token_id= np.argmax(probabilities,axis=-1)

print('Logits shape:', logits.shape)
print('Probabilities shape:', probabilities.shape)
print("row sums:", np.round(probabilities.sum(axis=-1), 4))
print("Predicted token id per position:", predicted_token_ids)

print('\nnext token prediction:')
print("Top id:", int(predicted_token_ids[-1]))
print("top probability:", float(np.max(probabilities[-1])))
# Output is random because so the prediction is not meaningful.
# I am going to train the model and show in below. 

Logits shape: (4, 20)
Probabilities shape: (4, 20)
row sums: [1. 1. 1. 1.]
Predicted token id per position: [15 15 15 15]

next token prediction:
Top id: 15
top probability: 0.8907736240137588


In [ ]:
# I built the transformer architecture with Numpy.
# I built  Q, K, V projections, scaling, softmax, multi head splitting, masking, positional encoding, encoder, decoder with cross attention, and the output layer.
# Every single step I printed the shapes and values so I can actually see what is happening.
# The attention weights sum to 1, that layer normalization brings mean to 0 and std to 1, and that the causal mask blocks future tokens.
# The cross-attention part: Q comes from the decoder, K and V come from the encoder, the encoder unmasked and only applied the causal mask in the decoder self attention.

<h2><center>PyTorch Transformer<h2>

In [137]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cpu


In [ ]:
# In here I am gonna show the architecture I built actually works
# when trained with real gradient descent

# # I am going to train it on simple task, copy a sequence of numbers.
# If the transformer can learn to copy, that proves the architecture works.

In [141]:
# In this cell, I am going to buil positional encoding class and wrapper model
# I add embedding layer and output linear layer after it.
#prepare for training on copy task

class PositionalEncodingTorch(nn.Module):
    def __init__(self, d_model, max_len=100):
        super().__init__()
        position_encoding = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        position_encoding[:, 0::2] = torch.sin(position * div_term)
        position_encoding[:, 1::2] = torch.cos(position * div_term)
# Saving the position encoding  inside the module as buffer
        self.register_buffer('position_encoding', position_encoding.unsqueeze(0))  
        
    def forward(self, x):
        return x + self.position_encoding[:, :x.size(1)]
    
class Transformer_model(nn.Module):
    def __init__(self, vocab_size, d_model, nhead, num_layers, dim_feedforward, dropout=0.1):
        super().__init__()
        self.d_model= d_model
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.position_encoder = PositionalEncodingTorch(d_model)

        self.transformer = nn.Transformer(d_model=d_model, nhead=nhead, num_encoder_layers=num_layers,
                                          num_decoder_layers=num_layers, dim_feedforward=dim_feedforward,dropout=dropout,
                                          batch_first=True)
        self.projection_out = nn.Linear(d_model, vocab_size)
        
    def forward(self, src, tgt, tgt_mask=None):
        source_token_ids_emb = self.position_encoder(self.embedding(src) * math.sqrt(self.d_model))
        target_token_ids_emb = self.position_encoder(self.embedding(tgt) * math.sqrt(self.d_model))
        output = self.transformer(source_token_ids_emb, target_token_ids_emb, tgt_mask=tgt_mask)

        return self.projection_out(output)
# Source: https://nlp.seas.harvard.edu/annotated-transformer/    

In [ ]:
# After building the model, in this cell, I am going to create data for training.
vocabulary_size = 11
dim_ff_pt = 128
number_of_heads = 2
number_of_layers = 2
model_dimension = 64
SOS = 0

def generate_copy_data(batch_size, sequence_length):
# Creating random sequences.
    data = torch.randint(1, vocabulary_size, (batch_size, sequence_length))
# source:  the sequence itself.
    source = data.clone()
    target_input = torch.cat([torch.zeros(batch_size, 1, dtype=torch.long), data[:, :-1]], dim=1)
    target_output = data.clone()
    return source, target_input, target_output
 
source_test, target_input_test, target_output_test = generate_copy_data(2, sequence_length)
print('source test shape:', source_test.shape)
print('target input test shape:', target_input_test.shape)
print('target output test shape:', target_output_test.shape)

source test shape: torch.Size([2, 10])
target input test shape: torch.Size([2, 10])
target output test shape: torch.Size([2, 10])


### Training loop

In [153]:
# TRAINING LOOP:
model = Transformer_model( vocab_size=vocabulary_size, d_model=model_dimension, nhead=number_of_heads,
                             num_layers=number_of_layers, dim_feedforward=dim_ff_pt, dropout=0.1).to(device)


optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

model.train()
for epoch in range(1000):
    source,target_input, tgt_output = generate_copy_data(128, sequence_length)
    tgt_mask = nn.Transformer.generate_square_subsequent_mask(target_input.size(1)).to(device)

    logits = model(source, target_input, tgt_mask=tgt_mask)
    loss = criterion(logits.reshape(-1, vocabulary_size), tgt_output.reshape(-1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) %200 == 0:
        print(f"Epoch {epoch + 1}, Loss: {loss.item():.4f}")


Epoch 200, Loss: 1.5401
Epoch 400, Loss: 0.9905
Epoch 600, Loss: 0.5250
Epoch 800, Loss: 0.3307
Epoch 1000, Loss: 0.2247


In [ ]:
# Evaluation:
model.eval()
correct = 0
total = 5

with torch.no_grad():
    test_src, _, _ = generate_copy_data(total, sequence_length)
    
    for i in range(total):
        source_single = test_src[i:i+1]
        generated = [SOS]
        
        for step in range(sequence_length):
            target_tensor = torch.tensor([generated], dtype=torch.long).to(device)
            tgt_mask = nn.Transformer.generate_square_subsequent_mask(len(generated)).to(device)
            output = model(source_single, target_tensor, tgt_mask=tgt_mask)
            next_token = output[0, -1].argmax().item()
            generated.append(next_token)
        
        input_seq = source_single[0].cpu().tolist()
        predicted = generated[1:]
        match= predicted == input_seq
        if match:
            correct += 1
        print(f'Input:{input_seq}')
        print(f"predicted:{predicted}")
print(f'Accuracy: {correct}/{total}')
# the model learned the copy rule quite well

Input:[10, 9, 4, 7, 3, 8, 8, 7, 3, 5]
predicted:[10, 9, 4, 7, 3, 8, 8, 7, 3, 5]
Input:[3, 3, 1, 9, 1, 5, 3, 4, 2, 8]
predicted:[3, 3, 1, 9, 1, 5, 3, 4, 2, 8]
Input:[6, 4, 3, 2, 3, 5, 2, 5, 7, 9]
predicted:[6, 4, 3, 2, 3, 5, 2, 5, 7, 9]
Input:[1, 2, 10, 3, 6, 10, 8, 7, 1, 3]
predicted:[1, 2, 10, 3, 6, 10, 8, 7, 1, 3]
Input:[2, 7, 9, 7, 1, 1, 7, 1, 5, 8]
predicted:[2, 7, 9, 7, 1, 1, 7, 5, 1, 8]
Accuracy: 4/5
