In [37]:
import math
import numpy as np


np.random.seed(0)

In [38]:
# First I am going to define single head attention from scratch.

<h2><center>Single Head Self Attention<h2>

In [39]:
# HYPERPARAMETERS:
sequence_length = 4
embedding_dimension = 8
# I defined hyperparameters for the attention mechanism.
# I need sequence length, embedding dimension, head dimension.
# Each word should have many different concepts, so embedding dimension is 8.

In [40]:
# TOKEN EMBEDDINGS:
token_embeddings = np.random.randn(sequence_length, embedding_dimension)
print("token_embeddings:")
print(token_embeddings.shape)
print(token_embeddings)

token_embeddings:
(4, 8)
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
   0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351  0.76103773  0.12167502
   0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574 -2.55298982  0.6536186
   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877
   0.15494743  0.37816252]]


In [41]:
# CREATING 3 DiFFERENT PRESPECTIVES FOR EACH TOKEN
# Query, Key, Value:
# These are weight metrices, in my notebook, these are randomm. But in transformer model, learned during training.
# Query (Q): what I am  looking for.
# Key (K): What can I offer??
# Value (V): What is my actual content?

# Each word becomes question asker 
W_q = np.random.randn(embedding_dimension,embedding_dimension)
# Each word becomes answer giver
W_k = np.random.randn(embedding_dimension, embedding_dimension)
# Each word becomes actual content
W_v =np.random.randn(embedding_dimension, embedding_dimension)
print("\nWeight matrices shapes:")
print("W_q shape:",W_q.shape)
print(W_q)
print("\nW_k shape:",W_k.shape)
print(W_k)
print("\nW_v shape:",W_v.shape)
print(W_v)


Weight matrices shapes:
W_q shape: (8, 8)
[[-0.88778575 -1.98079647 -0.34791215  0.15634897  1.23029068  1.20237985
  -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218 -0.4380743
  -1.25279536  0.77749036]
 [-1.61389785 -0.21274028 -0.89546656  0.3869025  -0.51080514 -1.18063218
  -0.02818223  0.42833187]
 [ 0.06651722  0.3024719  -0.63432209 -0.36274117 -0.67246045 -0.35955316
  -0.81314628 -1.7262826 ]
 [ 0.17742614 -0.40178094 -1.63019835  0.46278226 -0.90729836  0.0519454
   0.72909056  0.12898291]
 [ 1.13940068 -1.23482582  0.40234164 -0.68481009 -0.87079715 -0.57884966
  -0.31155253  0.05616534]
 [-1.16514984  0.90082649  0.46566244 -1.53624369  1.48825219  1.89588918
   1.17877957 -0.17992484]
 [-1.07075262  1.05445173 -0.40317695  1.22244507  0.20827498  0.97663904
   0.3563664   0.70657317]]

W_k shape: (8, 8)
[[ 0.01050002  1.78587049  0.12691209  0.40198936  1.8831507  -1.34775906
  -1.270485    0.96939671]
 [-1.17312341  1.94362119 -0.4

In [42]:
# In mumpy @ is matrix multiplication.
# Spurce: https://numpy.org/doc/2.1/reference/generated/numpy.matmul.html?

In [43]:
# This is like asking: For each word, what is its query vector, what it wants from others?
Q =token_embeddings @ W_q  
K= token_embeddings @ W_k 
V = token_embeddings @ W_v 
print("\nQury shape:shape:",Q.shape)
print(Q)
print("\nKey shape:",K.shape)
print(K)
print("\nValue shape:",V.shape)
print(V)


Qury shape:shape: (4, 8)
[[-5.14329841 -2.44018414 -6.52863207  0.51116581  0.49852547  2.30066161
  -0.30223837 -3.7632453 ]
 [-1.07542068  0.32630062 -2.83567179  0.30794017 -1.45413732  0.1395637
  -0.50192854 -1.8374508 ]
 [-1.59413038 -2.77831285  5.21829436 -3.60000123  5.23621887  2.22688508
  -0.94649399  0.02482593]
 [ 0.78431113 -4.38895788 -0.21823792 -2.46930639  1.27533979  3.27168043
   2.0709697  -0.95462633]]

Key shape: (4, 8)
[[ 2.61868617  5.32088725 -2.21285007  7.40470497  2.23937946 -2.9171613
  -3.10951834  9.45599857]
 [ 1.33168829 -0.28177695 -0.7635857   2.24792734 -1.18126044  0.01953494
  -0.52321681  4.300593  ]
 [ 0.93855483  4.05985713  1.44426359 -0.76083027  2.082033   -1.62971644
   0.80743105  0.46588887]
 [ 3.58543568  1.6722437   0.04461782  0.93055765 -1.35165464 -4.97687382
  -6.66446176  2.64844173]]

Value shape: (4, 8)
[[ 0.76755231 -2.83248751 -0.45197153 -0.23697617 -2.11506695  6.06838635
  -2.46877688 -1.27516318]
 [ 1.37649418 -3.33332497

In [44]:
# T stands for transpose to swap rows and columns in matrix for computing dot product.
#source:https://jtlicardo.com/blog/self-attention-mechanism

In [45]:
# Without scaling:
attention_scores = (Q @ K.T)
attention_scores

array([[-48.46115302, -16.59744429, -29.26081294, -42.41358894],
       [-12.00252904,  -4.5856329 ,  -8.5306868 ,  -3.40056023],
       [-48.75427426, -18.95702473,   4.01997717, -25.26571042],
       [-61.25555622,  -9.73463472, -16.96808943, -41.17160952]])

In [46]:
# Here I can see that the attention scores  are too big
# I am going to use softmax to convert them to probabilities.
# But with this big values, softmax will focus on large values.
# I need to scale them.
# Source: https://www.youtube.com/watch?v=0PjHri8tc1c

In [47]:
# ATTENSION SCORE: 
# Now I am going to calculate attention scores that I can see how each word attends to other words.
scale= np.sqrt(embedding_dimension)
attention_scores = (Q @ K.T)/ scale
# If I can explain clearly: 
# Word1 asks Q1, Word2 answers with K2 calculate match score
# Higher score = We understand each other well
# For example, scores: Word1 with Word2 = 0.9 which is high, Word1 with Word3 = 0.5, Word1 with Word4 = 0.1
print("\nAttention scores shape:",attention_scores.shape)
print(attention_scores)
# Now it looks better.
# 48/2.8 = 17.13


Attention scores shape: (4, 4)
[[-17.13360496  -5.8680827  -10.34525963 -14.99546818]
 [ -4.24353484  -1.62126606  -3.01605324  -1.2022796 ]
 [-17.23723897  -6.70232037   1.42127656  -8.93277758]
 [-21.6571096   -3.44171311  -5.99912555 -14.55636214]]


In [ ]:
# ATTENTION WEIGHT:
# Here, raw score is turned into probabilities like saying pay X%  attention here

def softmax(x, axis=-1):
    x_shifted= x - np.max(x, axis=axis,keepdims=True)
    exp_x= np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=axis,keepdims=True)
attention_weights= softmax(attention_scores)

# Softmax makes things differentiable and focuses on high scores while ignoring lows.
# Source: https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python
print("\nAttention weights shape:",attention_weights.shape)
print(attention_weights)
# here, the softmax made values in probability form.


Attention weights shape: (4, 4)
[[1.26615123e-05 9.88643541e-01 1.12363822e-02 1.07415409e-04]
 [2.55682235e-02 3.51995745e-01 8.72547416e-02 5.35181290e-01]
 [7.88074176e-09 2.96363089e-04 9.99671776e-01 3.18528907e-05]
 [1.13953720e-08 9.28057076e-01 7.19290918e-02 1.38211425e-05]]


In [ ]:
# CREATING NEW UNDERSTANDING:
# Here, each word creates a new version of itself by mixing other words information.
# The model learns contextual meaning
# Each word becomes smarter by considering its neighbors 
# For example: word bank can learn from account,bank account.
Attention_output= attention_weights @V
print("\nAttention output shape:",Attention_output.shape)
print(Attention_output)


Attention output shape: (4, 8)
[[ 1.34183768 -3.22302592  0.30127404  0.28646352  0.02777836  1.73761364
  -1.28251356  1.30731129]
 [-1.5554347   0.47820738  2.50183185  0.44145363 -1.2631944   1.10857787
   0.23516515 -2.13999061]
 [-1.65893093  6.42668607  0.5231314   1.19786552 -1.64813149 -3.65713874
  -6.388647   -7.97541717]
 [ 1.15802999 -2.63100225  0.31453943  0.34241596 -0.07491754  1.40636373
  -1.5963526   0.7378006 ]]


<h2><center>Multi Head Self attention and masking from scratch<h2>

In [50]:
# In here  I am going to create multi head attention from scratch,  multiple heads self attention mechanism is like having many brains.
# from what I understand, it helps the model focus on different parts of the input parallelly.
# In single head attention, I have one set of Q, K, V  per token. but here, I will have multiple sets of Q, K, V per token.

In [51]:
# For multi head attention, I am going to define some hyperparameters
# The frist one is going to be:
# Number of head attention, what I understand, it is like number of specialists for monitoring attention pattern
# While I was reading some articles, some LLMs use 128 heads.
# Second one is going to be: 
# I have to give equal capacity to each head to learn the patterns, So I divide the embedding dimension by number of heads.
num_heads = 2
# I have already  embedding_dimension which is 8, so each head can get 4 dimension to learn patterns.
head_dimension = embedding_dimension // num_heads 
head_dimension

4

In [52]:
# INPUT EMBEDDINGS:
# I need reproducible numbers
# transformer models use pretrained embeddings like word2vec, GloVe, FastText,BERT.
# real models get semantic meaning, similar words have similar vectors.
# In here, each word  has 8 traits.
token_embeddings_multi_heads = np.random.randn(sequence_length, embedding_dimension)
print("token_embeddings:", token_embeddings_multi_heads.shape)
print(token_embeddings_multi_heads)
# In output, I can see that 4 tokens, each has 8 demensions you know that is like 8 personality 
# What I learned, token embeddings give passport to each word in the sentence.

token_embeddings: (4, 8)
[[-1.54079701  0.06326199  0.15650654  0.23218104 -0.59731607 -0.23792173
  -1.42406091 -0.49331988]
 [-0.54286148  0.41605005 -1.15618243  0.7811981   1.49448454 -2.06998503
   0.42625873  0.67690804]
 [-0.63743703 -0.39727181 -0.13288058 -0.29779088 -0.30901297 -1.67600381
   1.15233156  1.07961859]
 [-0.81336426 -1.46642433  0.52106488 -0.57578797  0.14195316 -0.31932842
   0.69153875  0.69474914]]


In [53]:
# PROJECTION MATRICES:
# My raw word embeddings are not ready for attention, the next step is to transform  them into Query projections, Key projections, Value projections.
# Search query, from what I understand, this creates search query from learning and extracting of word that are relavant to ask questions.
# Key projection matrix learns to extract  that aspect of the word embeddings that  make useful 
# Value projection matrix makes the actual content 
# Output projection matrix,   
# Overall, I can say that projection matrices helps the model to learn different  roles for the same word.

W_Q = np.random.randn(embedding_dimension, embedding_dimension)
W_K =np.random.randn(embedding_dimension, embedding_dimension)
W_V= np.random.randn(embedding_dimension, embedding_dimension)
W_OutPut =np.random.randn(embedding_dimension, embedding_dimension)
# PROJECTING QUERY, KEY, VALUE:
# Now, I can create 3 different roles, Google News dataset model has 300 dimension vectors.
Q_Multi_Head = token_embeddings_multi_heads @ W_Q
K_Multi_Head = token_embeddings_multi_heads @ W_K
V_Multi_Head = token_embeddings_multi_heads @ W_V

print("Query Projection Matrix")
print(W_Q.shape)
print(W_Q)
print("\nKey Projection Matrix")
print(W_K.shape)
print(W_K)
print("\nValue Projection Matrix")
print(W_V.shape)
print(W_V)
print("\nOutput Projection Matrix")
print(W_OutPut.shape)
print(W_OutPut)

# What I can see here, from 8 demensions of each word, Query, Key, Value projections are created.

Query Projection Matrix
(8, 8)
[[-0.72559738 -1.38336396 -1.5829384   0.61037938 -1.18885926 -0.50681635
  -0.59631404 -0.0525673 ]
 [-1.93627981  0.1887786   0.52389102  0.08842209 -0.31088617  0.09740017
   0.39904635 -2.77259276]
 [ 1.95591231  0.39009332 -0.65240858 -0.39095338  0.49374178 -0.11610394
  -2.03068447  2.06449286]
 [-0.11054066  1.02017271 -0.69204985  1.53637705  0.28634369  0.60884383
  -1.04525337  1.21114529]
 [ 0.68981816  1.30184623 -0.62808756 -0.48102712  2.3039167  -1.06001582
  -0.1359497   1.13689136]
 [ 0.09772497  0.58295368 -0.39944903  0.37005589 -1.30652685  1.65813068
  -0.11816405 -0.6801782 ]
 [ 0.66638308 -0.46071979 -1.33425847 -1.34671751  0.69377315 -0.15957344
  -0.13370156  1.07774381]
 [-1.12682581 -0.73067775 -0.38487981  0.09435159 -0.04217145 -0.28688719
  -0.0616264  -0.10730528]]

Key Projection Matrix
(8, 8)
[[-0.71960439 -0.81299299  0.27451636 -0.89091508 -1.15735526 -0.31229225
  -0.15766702  2.2567235 ]
 [-0.70470028  0.94326072  0.

In [54]:
print("\nQ_Multi_Head shape:",Q_Multi_Head.shape)
print(Q_Multi_Head)
print("\nK_Multi_Head shape:",K_Multi_Head.shape)
print(K_Multi_Head)
print("\nV_Multi_Head shape:",V_Multi_Head.shape)
print(V_Multi_Head)


Q_Multi_Head shape: (4, 8)
[[ 4.47578083e-01  2.54158236e+00  4.76948068e+00  1.43119702e+00
  -7.66056412e-02  1.51768244e+00  7.13659381e-01 -1.48918392e+00]
 [-2.40950851e+00  1.22335049e+00  3.49875274e-01 -6.37415661e-01
   6.58371685e+00 -4.35317936e+00  1.96374714e+00  9.28000610e-01]
 [ 1.79169258e-01 -2.24789816e+00  4.20871333e-03 -2.75134780e+00
   2.96218145e+00 -2.82659596e+00  8.22140298e-01  2.41471879e+00]
 [ 4.25707194e+00 -3.63385788e-01 -5.73904191e-01 -2.76667391e+00
   2.70999678e+00 -1.13129300e+00 -6.73264833e-01  5.53626257e+00]]

K_Multi_Head shape: (4, 8)
[[-0.23032457  4.10990919 -0.69681036  2.80410693  2.87751884  0.82791391
   1.16373507 -4.4380722 ]
 [ 2.69795373 -2.48875856 -2.25648205 -3.11750308 -3.3461424  -0.41730036
  -2.65033961  0.57047362]
 [-0.1029719  -2.62172077 -1.53275905  0.17017102 -0.15136576  0.63415146
  -0.43448628 -1.15468744]
 [ 1.19009161 -2.29589606 -1.80537549  2.98481686 -0.82326731  1.52982212
   2.56926124 -2.68413999]]

V_Mul

In [55]:
# MULTI HEAD SPLITTING:
# iam going to create a function to split 8 dimension into 2 heads.
def split_heads(Input, num_heads):
    return Input.reshape(sequence_length, num_heads, head_dimension).transpose(1, 0, 2)

# COMBINING HEADS BACK:
def mergee_heads(heads):
    return heads.transpose(1, 0, 2).reshape(sequence_length, embedding_dimension)

# I defined the softmax function already above, when I printed projections, all 8 demensions are printed together or worked together.
# here each head  have half of that. 

In [56]:
# Now I can split the projections into two heads.
Q_heads = split_heads(Q_Multi_Head, num_heads)
K_heads= split_heads(K_Multi_Head, num_heads)
V_heads =split_heads(V_Multi_Head,num_heads)

print("Q_heads shape:",Q_heads.shape)
print(Q_heads)
print("K_heads shape:",K_heads.shape)
print(K_heads)
print("V_heads shape:",V_heads.shape)
print(V_heads)

Q_heads shape: (2, 4, 4)
[[[ 4.47578083e-01  2.54158236e+00  4.76948068e+00  1.43119702e+00]
  [-2.40950851e+00  1.22335049e+00  3.49875274e-01 -6.37415661e-01]
  [ 1.79169258e-01 -2.24789816e+00  4.20871333e-03 -2.75134780e+00]
  [ 4.25707194e+00 -3.63385788e-01 -5.73904191e-01 -2.76667391e+00]]

 [[-7.66056412e-02  1.51768244e+00  7.13659381e-01 -1.48918392e+00]
  [ 6.58371685e+00 -4.35317936e+00  1.96374714e+00  9.28000610e-01]
  [ 2.96218145e+00 -2.82659596e+00  8.22140298e-01  2.41471879e+00]
  [ 2.70999678e+00 -1.13129300e+00 -6.73264833e-01  5.53626257e+00]]]
K_heads shape: (2, 4, 4)
[[[-0.23032457  4.10990919 -0.69681036  2.80410693]
  [ 2.69795373 -2.48875856 -2.25648205 -3.11750308]
  [-0.1029719  -2.62172077 -1.53275905  0.17017102]
  [ 1.19009161 -2.29589606 -1.80537549  2.98481686]]

 [[ 2.87751884  0.82791391  1.16373507 -4.4380722 ]
  [-3.3461424  -0.41730036 -2.65033961  0.57047362]
  [-0.15136576  0.63415146 -0.43448628 -1.15468744]
  [-0.82326731  1.52982212  2.569261

In [ ]:
multi_head_scale = np.sqrt(head_dimension)

attention_weight_multi_head= np.zeros((num_heads, sequence_length, sequence_length))
head_outputs= np.zeros((num_heads,sequence_length,head_dimension))

# To process each head separately, I am going to use for loop.
for head in range(num_heads):
    scores_multi_head = (Q_heads[head] @K_heads[head].T) /multi_head_scale             
    weights= softmax(scores_multi_head)        
    out= weights @V_heads[head]                              

    attention_weight_multi_head[head] = weights
    head_outputs[head]= out

Combined_output= mergee_heads(head_outputs)
# What i noticed here form reeading 
# To mix information across both heads, I am going to use output projection matrix.
# Because in real models,  heads can collaborate. not stay isolated
Output_projection = Combined_output @ W_OutPut
print("attention_probability:", attention_weight_multi_head.shape)
print(attention_weight_multi_head)

print("\nOutput", head_outputs.shape)
print(head_outputs)
print("\nCombined output shape:",Combined_output.shape)
print(Combined_output)
print("\nFinal output shape:",Output_projection.shape)
print(Output_projection)
print("\nRow sums per head:\n", np.round(attention_weight_multi_head.sum(axis=-1), 4))

attention_probability: (2, 4, 4)
[[[9.99963332e-01 1.53870247e-07 4.10053267e-06 3.24137406e-05]
  [9.67739343e-01 2.52258338e-03 2.70362840e-02 2.70178972e-03]
  [1.33154827e-07 9.90113425e-01 9.72887147e-03 1.57570489e-04]
  [1.04818042e-07 9.99969812e-01 2.26947317e-05 7.38823758e-06]]

 [[5.18500317e-01 1.57476567e-03 2.46516988e-02 4.55273218e-01]
  [9.99921946e-01 4.59571476e-09 6.80848552e-05 9.96497395e-06]
  [6.76457873e-01 3.44044068e-02 2.73665270e-01 1.54724505e-02]
  [5.13095363e-04 8.55991247e-01 1.43312410e-01 1.83247828e-04]]]

Output (2, 4, 4)
[[[-1.45148693  2.15872919  1.57714082  1.54180617]
  [-1.3744429   2.12347454  1.4671084   1.67576157]
  [ 1.30218726  0.24450175 -1.75912919  9.16607769]
  [ 1.30594122  0.23714176 -1.75543164  9.2020129 ]]

 [[-3.31628422 -1.02623844 -1.22293786 -0.07069307]
  [-4.85507384 -0.54222589 -0.25492793  1.19276607]
  [-2.73979657 -0.74201718  0.11153973  1.16815948]
  [ 4.29976396 -0.16093631 -0.50145802  3.08532927]]]

Combined out

In [ ]:
# Sources:
# https://www.geeksforgeeks.org/nlp/multi-head-attention-mechanism
# https://www.datacamp.com/de/tutorial/multi-head-attention-transformers
# https://magazine.sebastianraschka.com/p/understanding-and-coding-self-attention
# https://www.kaggle.com/discussions/general/506393
# https://datajourney24.substack.com/p/inside-the-transformer-attention
# https://sungwookyoo.github.io/tips/study/Multihead_Attention
# https://blog.dailydoseofds.com/p/implement-attention-is-all-you-need
# https://agrimpaneru.com.np/blog/multi-head-attention-pytorch/
# https://medium.com/%40wangdk93/multihead-attention-from-scratch-6fd6f99b9651
# https://www.digitalocean.com/community/tutorials/multi-head-attention-simple-explained?
# For debugging, I used QWEN3 MAX model 

<h2><center>Masked Multi Head Attention<h2>

In [ ]:
# what I learned:
# Biredictional attention like BERT model, can see context from both  directions.
# and casual attention can see only previous words.

# triu is  triangular upper, 
# https://www.mindspore.cn/docs/api/en/r1.6/api_python/nn/mindspore.nn.Triu.html?

# To force the model to predict next word.
def causal_mask(sequence_length):
 # Here I the attenion for next is masked
    return np.triu(np.ones((sequence_length, sequence_length), dtype=bool), k=1)

causal_mask= causal_mask(sequence_length)

# Again, I am going to use for loop to get causal mask in attention calculation.
for head in range(num_heads):
    # Copying above scores
    scores_multi_head =scores_multi_head.copy()  
    scores_multi_head[causal_mask]= -np.inf 
    weights =softmax(scores_multi_head)
    out =weights @V_heads[head]

    attention_weight_multi_head[head]= weights
    head_outputs[head]= out

print("Causal mask:", causal_mask.astype(int))
print("attention_probability with causal mask:", attention_weight_multi_head.shape)


Causal mask: [[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]
attention_probability with causal mask: (2, 4, 4)


<h2><center>Encoder block<h2>

In [ ]:
# LAYER NORMALIZATION:
# To normalize each token separately, before processing, I can use layer normalization.  
# Calcaulating  average of all 8 demensions for tken. 
def layer_normalization(x,epsilon = 0.00001):
    mean = x.mean(axis=-1, keepdims=True)
    variance= x.var(axis=-1, keepdims=True)
    normalized_x = (x -mean)/ np.sqrt(variance+ epsilon)
    return normalized_x

x1 = layer_normalization(token_embeddings_multi_heads + Output_projection)
x1
#  in real models,  layer normalization apply gamma and beta afterward

array([[-0.23793323, -0.30976864,  1.74463472,  0.59935388, -0.84960496,
         0.9823896 , -1.63419152, -0.29487986],
       [-0.52110109, -0.81457811,  1.28682346,  0.46592678, -0.85354551,
         1.70975523, -1.24058029, -0.03270049],
       [-1.00132315, -1.91677372,  1.23331294,  0.60677925,  0.69475696,
        -0.6458158 ,  0.56370861,  0.4653549 ],
       [-0.48051199, -1.18605476,  0.272184  , -0.05224626,  0.88761819,
        -1.67859017,  1.41596033,  0.82164067]])

In [ ]:
# FEED FORWARD NETWORK: 
# Like other neural networks, The transformer model should learn nonlinear patterns.
# Here I have two linear layers with one relu activation in the middle.
latent_dimension= 16 
Weights_matrix1 = np.random.randn(embedding_dimension, latent_dimension)
Bias1= np.zeros((latent_dimension,))

Weights_matrix2 =np.random.randn(latent_dimension, embedding_dimension)
Bias2 =np.zeros((embedding_dimension,))


def relu(x):
    return np.maximum(0, x)

Hidden = relu(x1 @Weights_matrix1 + Bias1)
OutPut= Hidden@ Weights_matrix2 +Bias2

x2= layer_normalization(x1 + OutPut )


print("x1 shape:", x1.shape)
print("Feed forward  Network Output shape:",OutPut.shape)
print("x2 shape:", x2.shape)

print("\n token mean :",np.round(x2.mean(axis=-1), 4))
print(" token std :", np.round(x2.std(axis=-1), 4))

x1 shape: (4, 8)
Feed forward  Network Output shape: (4, 8)
x2 shape: (4, 8)

 token mean : [0. 0. 0. 0.]
 token std : [1. 1. 1. 1.]


<h2><center>Output Layer<h2>

In [66]:
# OUTPUT LAYER: 
# In this cell, I am going to converts each row into scores for every vocabulary token
# In real library, that is called logits

vocablry_size = 20 
# Here unembedding 
Weight_vocab =np.random.randn(embedding_dimension, vocablry_size)
b_vocab= np.zeros((vocablry_size,))

Logits= x2 @Weight_vocab+ b_vocab
# Applying softmax to get probability        
Probabilities= softmax(Logits, axis=-1) 

Predicted_token_id= np.argmax(Probabilities,axis=-1)

print("Logits shape:", Logits.shape)
print("Probabilities shape:", Probabilities.shape)
print("Row sums:", np.round(Probabilities.sum(axis=-1), 4))
print("Predicted_token_id per position:", Predicted_token_id)

print("\nNext token prediction:")
print("Top id:", int(Predicted_token_id[-1]))
print("Top probability:", float(np.max(Probabilities[-1])))


Logits shape: (4, 20)
Probabilities shape: (4, 20)
Row sums: [1. 1. 1. 1.]
Predicted_token_id per position: [7 7 1 1]

Next token prediction:
Top id: 1
Top probability: 0.5143953992508514
